version: 2
updates:
  - package-ecosystem: npm
    directory: /
    labels:
      - dependencies
    schedule:
      interval: daily
      time: "00:00"
  - package-ecosystem: github-actions
    directory: /
    labels:
      - dependencies
    schedule:
      interval: daily
      time: "00:00"
